# As inputs and outputs of each script may clash
# (you don't want to ovewrite the the hardly won results of previous scripts)
# I will separate scripts into different branches of the yaml tree
# then the configuration at the start of each script
# will read it's own options and the shared/general options
# this way I have a record of the deafault values at each step
# In any case the output is probably better called  output
# at every step no matter the script. This mitigates the risk of over writing.
shared:
  config_file: $GEA_CONFIG
  pheno_dir: /rsstu/users/r/rrellan/sara/SorghumGEA/data/Lasky2015/traits
  output_dir: gea_out
  batch_test_dir: $GEA_EXTDATA/batch_test
  # Sorghum bicolor chromosome 10
  geno_test_file: /rsstu/users/r/rrellan/sara/SorghumGEA/data/Lasky2015/sb_snpsDryad_sept2013_filter.c10.imp.hmp.txt

make_hapmap_geo_loc:
  id_map: /rsstu/users/r/rrellan/sara/SorghumGEA/data/Lasky2015/hapmap_ids.txt
  geo_loc: /rsstu/users/r/rrellan/sara/SorghumGEA/data/Lasky2015/geo_loc.csv
  hapmap_geo_loc: gea_out/hapmap_geo_loc.tassel

make_phenotype_table:
  # probability of very low  P solubility raster
  raster_file: /rsstu/users/r/rrellan/sara/SorghumGEA/data/soilP/sol_VL.tif
  #probabilty of very low P solubility table TASSEL4 format
  pheno_file: gea_out/sol_VL.tassel

run_GLM:
  glm_prefix: glm
# here we have moved the file to a more permanent destination
  pheno_file: /rsstu/users/r/rrellan/sara/SorghumGEA/data/Lasky2015/traits/sol_VL.tassel
  geno_file:  /rsstu/users/r/rrellan/sara/SorghumGEA/data/Lasky2015/filtered/Lasky2015_c10_001.hmp.txt

make_kinship_matrix:
  km_prefix: km
  mds_prefix: mds
  geno_dir:  /rsstu/users/r/rrellan/sara/SorghumGEA/data/Lasky2015/kinship_sample
  pheno_file: /rsstu/users/r/rrellan/sara/SorghumGEA/data/Lasky2015/traits/sol_VL.tassel
  geno_file:  /rsstu/users/r/rrellan/sara/SorghumGEA/data/Lasky2015/kinship_sample/loco_chr_1.hmp.txt

run_MLM:
  mlm_prefix: mlm
  geno_dir: /rsstu/users/r/rrellan/sara/SorghumGEA/data/Lasky2015/filtered
  kinship_matrix: /rsstu/users/r/rrellan/sara/SorghumGEA/results/kinship_20220301/km/km_loco_10.RDS
  pheno_file: /rsstu/users/r/rrellan/sara/SorghumGEA/data/Lasky2015/traits/sol_VL.tassel
  geno_file:  /rsstu/users/r/rrellan/sara/SorghumGEA/data/Lasky2015/filtered/Lasky2015_c10_001.hmp.txt

plot_manhattan:
  # here we have moved the file to a more permanent destination
  trait: sol_VL
  rds_dir: gea_out/rds
  png_dir: gea_out/png

