# General -------------------------------------------------
config: $GEA_CONFIG
geno_dir: /rsstu/users/r/rrellan/sara/SorghumGEA/data/Lasky2015/snpsLaskySciAdv_dryad
pheno_dir: /rsstu/users/r/rrellan/sara/SorghumGEA/data/Lasky2015/traits
output_dir: gea_out
batch_test_dir: $GEA_EXTDATA/batch_test

# very low P solubility probabilty table TASSEL4 format
<<<<<<< HEAD
pheno_file: GEA_output/sol_VL.tassel
=======
# pheno_file: gea_out/sol_VL.tassel
>>>>>>> 9e2f7a3ce68806875e98e96faf0f4156a6db5b95
# Sorghum bicolor chromosome 10
geno_file: /rsstu/users/r/rrellan/sara/SorghumGEA/data/Lasky2015/snpsLaskySciAdv_dryad/sb_snpsDryad_sept2013_filter.c10.imp.hmp.txt

# make_hapmap_geo_loc.R -----------------------------------
id_map: /rsstu/users/r/rrellan/sara/SorghumGEA/data/Lasky2015/hapmap_ids.txt
geo_loc: /rsstu/users/r/rrellan/sara/SorghumGEA/data/Lasky2015/geo_loc.csv
hapmap_geo_loc: gea_out/hapmap_geo_loc.tassel

# make_phenotype_table.R -----------------------------------
# very low P solubility probabilty raster
raster_file: /rsstu/users/r/rrellan/sara/SorghumGEA/data/soilP/sol_VL.tif

# run_GLM.R ------------------------------------------------
glm_prefix: glm

# run_MM.R -------------------------------------------------
mm_prefix: mm
