shared:
  config_file: $GEA_CONFIG
  pheno_dir: /Users/fvrodriguez/Desktop/sorghum
  output_dir: /Users/fvrodriguez/Desktop/sorghum/gea_out
  batch_test_dir: $GEA_EXTDATA/batch_test

make_hapmap_geo_loc:
  id_map: /Users/fvrodriguez/Desktop/sorghum/hapmap_ids.txt
  geo_loc: /Users/fvrodriguez/Desktop/sorghum/geo_loc.csv
  hapmap_geo_loc: /Users/fvrodriguez/Desktop/sorghum/gea_out/hapmap_geo_loc.tassel

make_phenotype_table:
  # very low P solubility probabilty raster
  hapmap_geo_loc: /Users/fvrodriguez/Desktop/sorghum/gea_out/hapmap_geo_loc.tassel
  raster_file: /Users/fvrodriguez/Desktop/sorghum/soilP_raster/sol_VL.tif
  pheno_file:  /Users/fvrodriguez/Desktop/sorghum/gea_out/sol_VL.tassel

run_GLM:
  glm_prefix: glm
  geno_dir: /Users/fvrodriguez/Desktop/sorghum
  # very low P solubility probabilty table TASSEL4 format
  pheno_file: /Users/fvrodriguez/Desktop/sorghum/gea_out/sol_VL.tassel
  geno_file:  /Users/fvrodriguez/Desktop/sorghum/sb_snpsDryad_sept2013_filter.c9.imp.hmp.txt

make_kinship_matrix:
  km_prefix: km
  mds_prefix: mds
  geno_dir: /Users/fvrodriguez/Desktop/sorghum
  pheno_file: /Users/fvrodriguez/Desktop/sorghum/gea_out/sol_VL.tassel
  geno_file:  /Users/fvrodriguez/Desktop/sorghum/kinship_sample/loco_chr_10.hmp.txt

run_MLM:
  mlm_prefix: mlm
  geno_dir: /Users/fvrodriguez/Desktop/sorghum
  kinship_matrix: /Users/fvrodriguez/Desktop/sorghum/kinship/km/km_loco_10.RDS
 # pop_str_file: /Users/fvrodriguez/Desktop/sorghum/gea_out/sol_VL.tassel
  pheno_file: /Users/fvrodriguez/Desktop/sorghum/gea_out/sol_VL.tassel
  geno_file:  /Users/fvrodriguez/Desktop/sorghum/sb_snpsDryad_sept2013_filter.c10.imp.hmp.txt

plot_manhattan:
  trait: sol_VL
  rds_dir: /Users/fvrodriguez/Desktop/sorghum/gea_out/rds
  png_dir: /Users/fvrodriguez/Desktop/sorghum/gea_out/png




